In [10]:
import pandas as pd
import numpy as np

In [11]:
base = pd.read_csv("aeroportoGuarulhos_2025.csv", sep=';')

In [12]:
base.head(30)

,Data,Hora (UTC),Temp. [Hora] (C),Umi. (%),Pressao (hPa),Vel. Vento (m/s),Dir. Vento (m/s),Nebulosidade (Decimos),Insolacao (h),Temp. Max. [Diaria] (h),Temp. Min. [Diaria] (h),Chuva [Diaria] (mm)
0,01/01/2025,0,"21,1","86,0","929,6","1,5","120,0","7,5",NaN,"30,1",NaN,NaN
1,01/01/2025,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/01/2025,600,"19,3","93,0","928,5","2,6","90,0","6,3",NaN,NaN,NaN,NaN
3,01/01/2025,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/01/2025,1200,"24,1","73,0","930,3","1,0","80,0","0,0",NaN,NaN,"18,5","8,0"
5,01/01/2025,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,01/01/2025,1800,"25,7","62,0","927,5","4,6","150,0","7,5",NaN,NaN,NaN,NaN
7,01/01/2025,2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,02/01/2025,0,"21,8","89,0","929,3","1,5","140,0","10,0",NaN,"31,5",NaN,NaN
9,02/01/2025,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,02/01/2025,600,"19,3","93,0","928,0","4,1","70,0","0,0",NaN,NaN,NaN,NaN
11,02/01/2025,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,02/01/2025,1200,"25,5","63,0","928,7","3,1","360,0","8,8",NaN,NaN,"18,4","1,0"
13,02/01/2025,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,02/01/2025,1800,"31,1","43,0","925,3","6,7","290,0","7,5",NaN,NaN,NaN,NaN
15,02/01/2025,2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,03/01/2025,0,"22,2","84,0","928,0","4,1","70,0","7,5",NaN,"30,4",NaN,NaN
17,03/01/2025,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,03/01/2025,600,"20,6","90,0","925,3","1,0","80,0","2,5",NaN,NaN,NaN,NaN
19,03/01/2025,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,03/01/2025,1200,"25,5","67,0","927,1","6,2","320,0","5,0",NaN,NaN,"20,4","0,4"
21,03/01/2025,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,03/01/2025,1800,"30,3","54,0","924,4","6,7","310,0","7,5",NaN,NaN,NaN,NaN
23,03/01/2025,2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,04/01/2025,0,"23,5","79,0","926,1","3,1","360,0","6,3",NaN,"29,9",NaN,NaN
25,04/01/2025,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,04/01/2025,600,"22,4","76,0","924,8","3,1","310,0","3,8",NaN,NaN,NaN,NaN
27,04/01/2025,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,04/01/2025,1200,"25,6","66,0","926,9","4,6","320,0","7,5",NaN,NaN,"21,6","0,5"
29,04/01/2025,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# 1. Fazemos uma cópia para não alterar a base original
df_tratado = base.copy()

# 2. Agrupamos por 'Data' e usamos ffill (forward fill) e bfill (backward fill).
# Isso faz com que os valores não-nulos (como Temp. Max e Chuva) preencham 
# os NaNs das outras horas do mesmo dia.
df_tratado = df_tratado.groupby('Data').transform(lambda x: x.ffill().bfill())

# 3. O comando .transform() remove a coluna que usamos para agrupar ('Data').
# Então, nós a devolvemos para o dataframe:
df_tratado['Data'] = base['Data']

# 4. Agora que os dados estão completos em todas as horas, filtramos só a linha das 12:00
# (Verifique se a sua coluna Hora é um número inteiro 1200 ou string "1200")
base_final = df_tratado[df_tratado['Hora (UTC)'] == 1200].copy()

# 5. Organizando o índice para ficar limpo (0, 1, 2, 3...)
base_final = base_final.reset_index(drop=True)

coluna_data = base_final.pop('Data')

# Insere a coluna 'Data' na posição 0 (primeira da esquerda)
base_final.insert(0, 'Data', coluna_data)

# Visualizando o resultado
display(base_final.head())

/tmp/ipykernel_9337/2775253680.py:7: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_tratado = df_tratado.groupby('Data').transform(lambda x: x.ffill().bfill())

,Data,Hora (UTC),Temp. [Hora] (C),Umi. (%),Pressao (hPa),Vel. Vento (m/s),Dir. Vento (m/s),Nebulosidade (Decimos),Insolacao (h),Temp. Max. [Diaria] (h),Temp. Min. [Diaria] (h),Chuva [Diaria] (mm)
0,01/01/2025,1200,"24,1","73,0","930,3","1,0","80,0","0,0",NaN,"30,1","18,5","8,0"
1,02/01/2025,1200,"25,5","63,0","928,7","3,1","360,0","8,8",NaN,"31,5","18,4","1,0"
2,03/01/2025,1200,"25,5","67,0","927,1","6,2","320,0","5,0",NaN,"30,4","20,4","0,4"
3,04/01/2025,1200,"25,6","66,0","926,9","4,6","320,0","7,5",NaN,"29,9","21,6","0,5"
4,05/01/2025,1200,"25,7","66,0","927,2","2,6","300,0","1,3",NaN,"28,5","18,5","14,0"

In [14]:
base_final = base_final.drop(columns=['Hora (UTC)', 'Insolacao (h)'])

In [15]:
base_final

,Data,Temp. [Hora] (C),Umi. (%),Pressao (hPa),Vel. Vento (m/s),Dir. Vento (m/s),Nebulosidade (Decimos),Temp. Max. [Diaria] (h),Temp. Min. [Diaria] (h),Chuva [Diaria] (mm)
0,01/01/2025,"24,1","73,0","930,3","1,0","80,0","0,0","30,1","18,5","8,0"
1,02/01/2025,"25,5","63,0","928,7","3,1","360,0","8,8","31,5","18,4","1,0"
2,03/01/2025,"25,5","67,0","927,1","6,2","320,0","5,0","30,4","20,4","0,4"
3,04/01/2025,"25,6","66,0","926,9","4,6","320,0","7,5","29,9","21,6","0,5"
4,05/01/2025,"25,7","66,0","927,2","2,6","300,0","1,3","28,5","18,5","14,0"
...,...,...,...,...,...,...,...,...,...,...
360,27/12/2025,"26,5","74,0","931,3","2,1","50,0","6,3","35,7","21,3","0,0"
361,28/12/2025,"27,3","70,0","929,3","2,1","40,0","0,0","36,4","20,2","0,5"
362,29/12/2025,"26,2","70,0","929,6","2,6","310,0","7,5","34,5","21,5","2,0"
363,30/12/2025,"24,7","79,0","930,3","4,1","60,0","6,3","34,3","20,8","14,0"
364,31/12/2025,"26,5","69,0","931,4","5,1","320,0","10,0","32,0","21,0","3,0"

In [16]:
# Verifica os tipos e valores das colunas
print("Tipos de dados:")
print(base_final.dtypes)
print("\nPrimeiras linhas:")
print(base_final.head())
print("\nNomes das colunas:")
print(base_final.columns.tolist())

Tipos de dados:
Data                       object
Temp. [Hora] (C)           object
Umi. (%)                   object
Pressao (hPa)              object
Vel. Vento (m/s)           object
Dir. Vento (m/s)           object
Nebulosidade (Decimos)     object
Temp. Max. [Diaria] (h)    object
Temp. Min. [Diaria] (h)    object
Chuva [Diaria] (mm)        object
dtype: object

Primeiras linhas:
         Data Temp. [Hora] (C) Umi. (%) Pressao (hPa) Vel. Vento (m/s)  \
0  01/01/2025             24,1     73,0         930,3              1,0
1  02/01/2025             25,5     63,0         928,7              3,1
2  03/01/2025             25,5     67,0         927,1              6,2
3  04/01/2025             25,6     66,0         926,9              4,6
4  05/01/2025             25,7     66,0         927,2              2,6

  Dir. Vento (m/s) Nebulosidade (Decimos) Temp. Max. [Diaria] (h)  \
0             80,0                    0,0                    30,1
1            360,0                    8,8                    31,5
2            320,0                    5,0                    30,4
3            320,0                    7,5                    29,9
4            300,0                    1,3                    28,5

  Temp. Min. [Diaria] (h) Chuva [Diaria] (mm)
0                    18,5                 8,0
1                    18,4                 1,0
2                    20,4                 0,4
3                    21,6                 0,5
4                    18,5                14,0

Nomes das colunas:
['Data', 'Temp. [Hora] (C)', 'Umi. (%)', 'Pressao (hPa)', 'Vel. Vento (m/s)', 'Dir. Vento (m/s)', 'Nebulosidade (Decimos)', 'Temp. Max. [Diaria] (h)', 'Temp. Min. [Diaria] (h)', 'Chuva [Diaria] (mm)']

In [17]:
df = base_final.copy()

# Substitui vírgulas por pontos em TODAS as colunas numéricas
colunas_numericas = [
    "Temp. [Hora] (C)", 
    "Chuva [Diaria] (mm)", 
    "Umi. (%)", 
    "Nebulosidade (Decimos)",
    "Pressao (hPa)",
    "Vel. Vento (m/s)",
    "Dir. Vento (m/s)",
    "Temp. Max. [Diaria] (h)",
    "Temp. Min. [Diaria] (h)"
]

for col in colunas_numericas:
    df[col] = df[col].astype(str).str.replace(',', '.')
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Preenche NaN com a mediana (ou 0 para chuva)
df["Temp. [Hora] (C)"] = df["Temp. [Hora] (C)"].fillna(df["Temp. [Hora] (C)"].median())
df["Chuva [Diaria] (mm)"] = df["Chuva [Diaria] (mm)"].fillna(0)
df["Umi. (%)"] = df["Umi. (%)"].fillna(df["Umi. (%)"].median())
df["Nebulosidade (Decimos)"] = df["Nebulosidade (Decimos)"].fillna(df["Nebulosidade (Decimos)"].median())
df["Pressao (hPa)"] = df["Pressao (hPa)"].fillna(df["Pressao (hPa)"].median())
df["Vel. Vento (m/s)"] = df["Vel. Vento (m/s)"].fillna(df["Vel. Vento (m/s)"].median())
df["Dir. Vento (m/s)"] = df["Dir. Vento (m/s)"].fillna(df["Dir. Vento (m/s)"].median())
df["Temp. Max. [Diaria] (h)"] = df["Temp. Max. [Diaria] (h)"].fillna(df["Temp. Max. [Diaria] (h)"].median())
df["Temp. Min. [Diaria] (h)"] = df["Temp. Min. [Diaria] (h)"].fillna(df["Temp. Min. [Diaria] (h)"].median())

# padroniza data
df["Data"] = pd.to_datetime(df["Data"], dayfirst=True)

# cria variáveis de calendário
df["dia_semana"] = df["Data"].dt.dayofweek
df["fim_de_semana"] = (df["dia_semana"] >= 5).astype(int)
df["mes"] = df["Data"].dt.month

# feriados simples
feriados = [
    "2025-01-01", "2025-04-21", "2025-05-01",
    "2025-09-07", "2025-10-12", "2025-11-02",
    "2025-11-15", "2025-11-20", "2025-12-25"
]
df["feriado"] = df["Data"].astype(str).isin(feriados).astype(int)

np.random.seed(42)

# promoção mais comum em fim de semana
df["promocao"] = np.where(
    df["fim_de_semana"] == 1,
    np.random.binomial(1, 0.25, len(df)),
    np.random.binomial(1, 0.10, len(df))
)

# use os nomes REAIS das colunas
df["dia_quente"] = (df["Temp. [Hora] (C)"] >= 30).astype(int)
df["chuva_forte"] = (df["Chuva [Diaria] (mm)"] >= 10).astype(int)

ruido = np.random.normal(0, 8, len(df))

df["vendas_sorvete"] = (
    80
    + 7.0 * df["Temp. [Hora] (C)"]
    - 1.2 * df["Chuva [Diaria] (mm)"]
    - 0.15 * df["Umi. (%)"]
    - 0.8 * df["Nebulosidade (Decimos)"]
    + 22 * df["fim_de_semana"]
    + 28 * df["feriado"]
    + 18 * df["promocao"]
    + 12 * df["dia_quente"]
    - 10 * df["chuva_forte"]
    + ruido
)

# Remove qualquer NaN ou infinito
df["vendas_sorvete"] = df["vendas_sorvete"].fillna(80)
df["vendas_sorvete"] = df["vendas_sorvete"].replace([np.inf, -np.inf], 80)

df["vendas_sorvete"] = df["vendas_sorvete"].clip(lower=40).round().astype(int)

df.head()

,Data,Temp. [Hora] (C),Umi. (%),Pressao (hPa),Vel. Vento (m/s),Dir. Vento (m/s),Nebulosidade (Decimos),Temp. Max. [Diaria] (h),Temp. Min. [Diaria] (h),Chuva [Diaria] (mm),dia_semana,fim_de_semana,mes,feriado,promocao,dia_quente,chuva_forte,vendas_sorvete
0,2025-01-01,24.1,73.0,930.3,1.0,80.0,0.0,30.1,18.5,8.0,2,0,1,1,0,0,0,259
1,2025-01-02,25.5,63.0,928.7,3.1,360.0,8.8,31.5,18.4,1.0,3,0,1,0,1,0,0,255
2,2025-01-03,25.5,67.0,927.1,6.2,320.0,5.0,30.4,20.4,0.4,4,0,1,0,1,0,0,264
3,2025-01-04,25.6,66.0,926.9,4.6,320.0,7.5,29.9,21.6,0.5,5,1,1,0,0,0,0,281
4,2025-01-05,25.7,66.0,927.2,2.6,300.0,1.3,28.5,18.5,14.0,6,1,1,0,0,0,1,251

In [18]:
# Salva o dataframe em CSV com separador ";" e ponto como decimal
df.to_csv('vendas_sorvete_final.csv', sep=';', index=False, encoding='utf-8', decimal='.')
print("Arquivo 'vendas_sorvete_final.csv' salvo com sucesso!")

Arquivo 'vendas_sorvete_final.csv' salvo com sucesso!